main.go
Add PATCH and DELETE methods to CORS because we do expose some of those in our endpoints.
(cherry picked from commit 9445d93)
=> Add warning when CORS feature is disabled.

device/datastore.go, migrations/201607100001_devices_unlock_token_down.sql, migrations/201607100001_devices_unlock_token_up.sql
Store unlock_token on TokenUpdate message.
(cherry picked from commit bcb16fc)
=> Add column unlock_token

enroll/endpoint.go, enroll/service.go, enroll/transport.go, main.go
A compilation of cherry picked commits regarding the enrollment endpoint and enrollment configuration variables.
Some changes to CORS, installed applications, and installed certificates were edited out.
Mostly this builds on the original enroll endpoint which had some hard coded values and makes them all configurable.
=> Enrollment

applications/application.go, applications/datastore.go, applications/datastore_test.go, applications/statement.go, connect/service.go, connect/service_test.go, enroll/profile.go, enroll/service.go, main.go, management/endpoint_installedapps.go, management/service.go, management/transport.go, management/transport_test.go, migrations/201607110001_applications_down.sql, migrations/201607110001_applications_up.sql, migrations/201608150001_devices_applications_down.sql, migrations/201608150001_devices_applications_up.sql
These commits relate to the installed applications service for acknowledging and querying lists of installed applications on a per device basis.
There's no unique constraint that will work for applications because some bundles have a name and no version etc. Therefore the entire list is replaced every time the device updates it.
Also more kludge/bits and pieces that should be in other branches.
=> Installed application list

command/datastore.go, command/datastore_test.go, command/endpoint.go, command/service.go, command/transport.go, connect/service.go
PR 16 (commands_management) with fixes per review by groob. Incl connect service conflict merge.
=> Commands management plus fixes

device/device.go
Regressioin introduced in #34
Fixes #36
=> Update missing time.Time from pointer to value fields.

driver/driver.go, driver/redis.go, driver/sqlx.go
Adding a few reusable helpers for establishing postgres and redis connections.
=> add utility package for establishing db driver connections

app/http.go, app/services.go, checkin/endpoint.go, checkin/service.go, checkin/transport_test.go, depenroll/endpoint.go, depenroll/service.go, depenroll/transport.go
=> move DEP enrollment to new service

app/config.go, app/services.go, checkin/archive/archive.go, checkin/service.go, checkin/service/direct/direct.go, checkin/service/event/service.go, checkin/transport.go, command/service/bolt/bolt.go, event/checkin.go
add checkin/service/event package
add checkin/service/archive package
add bolt.db version of command/service
make -dep flag optional
make -redis flag optional -defaults to boltdb command service
=> create event-based checkin service

app/config.go, app/crypto.go, app/envutils.go, app/http.go, app/services.go
makes TLS certificate optional and generates one if not provided
in config.
=> app: generate self-signed TLS cert at startup

README.md
=> Read me cleanup

device/db.go, device/db_test.go
This change makes it easier to range over the device bucket.
Also added some necessary tests for this package.
=> save device indexes in a separate bucket

deptoken.go, main.go, serve.go
rename flags and add export option
only run DEPSim if flag is explicitly provided.
=> rename deptoken flags and add JSON token export

.gitignore, main.go, release.sh, version/version.go
=> add version command

lock.json, serve.go
=> Log all HTTP requests with gorilla handlers.CombinedLoggingHandler

CONTRIBUTING.md, README.md
The bare minimum :)
Will leave up for a bit if anyone else has any suggestions or spots something odd.
=> add contribution page

cmd/mdmctl/list.go, cmd/mdmctl/mdmdctl.go, core/list/client.go, core/list/endpoint.go, core/list/service.go, core/list/transport_http.go, device/db.go, serve.go
this is the beginning of #110 and #82.
Using the example here: https://github.com/go-kit/kit/tree/master/examples/addsvc
=> [WIP] add list devices api

device/db.go
Closes #124
The UUID enforces uniqueness in the db. If a device is already
re-enrolling, don't create a new record.
=> only create a UUID on initial enrollment

cmd/mdmctl/list.go, core/list/client.go, serve.go
uses basic auth to set/read token
=> Add authentication to mdmctl and server

cmd/mdmctl/config.go, cmd/mdmctl/get.go, cmd/mdmctl/mdmdctl.go
update the params of ~/.micromdm/default.json using the CLI
```
mdmctl config set -api-token=foobar -server-url=xyz.abcd.co/a/b/c/d;cat ~/.micromdm/default.json                                   
{
"api_token": "foobar",
"server_url": "https://xyz.abcd.co/"
}
```
=> add config set command

cmd/mdmctl/config.go
Also use more secure file mode bits for default.json.
=> Make ~/.micromdm if it does not exist

serve.go
Quick check to confirm filerepo path exists. Bail if it dosn't.
=> Add validation that filerepo path exists

blueprint/db.go, cmd/mdmctl/apply.go, cmd/mdmctl/get.go, core/apply/endpoint.go, core/apply/transport_http.go, core/list/client.go, core/list/endpoint.go, core/list/service.go, core/list/transport_http.go, serve.go
Start work on apply/get/list for blueprints. Note this PR is based off some work in the (as-yet-not-merged #141), though it should be fairly independent code-wise of it (just some conflict/merge concerns).
=> Blueprint apply & get/list

serve.go
=> Add optional -config-path flag and base all other paths off this location

depsync/depsync.go
=> save DEP cursor during fetch/sync ops

push/service.go
See #150 for history & research.
=> Better error message for APNs certificate expiry

core/apply/client.go, core/apply/endpoint.go, core/apply/service.go, core/apply/service_dep.go, core/apply/transport_http.go, core/list/client.go, core/list/endpoint.go, core/list/service.go, core/list/service_dep.go, core/list/transport_http.go, serve.go
for #154 
This PR creates the server endpoints for the `get dep` interactions:
- account info
- device details
- profiles
The `mdmctl` implementation will come in a separate PR.
=> create DEP commands for the list/apply services

CHANGELOG.md, serve.go
=> Put push and command APIs behind API authentication middleware

cmd/mdmctl/apply.go
For #162 
The updated command is:
```
mdmctl apply blueprints -template
{
"uuid": "4a65c558-ecab-40e5-91ce-6e4a7f3ad318",
"name": "exampleName",
"install_application_manifest_urls": [
"https://mdmdev.corp.kolide.co/repo/exampleAppManifest.plist"
],
"profile_ids": [
"com.example.my.profile"
],
"apply_at": null
}
```
=> update generate blueprint command to print to stdout

Gopkg.lock, blueprint/listener.go, command/command_test.go
Add breaking changes from upstream.
=> upstream changes from micromdm/mdm

cmd/mdmctl/get.go
`-f -` writes output to stdout.
=> support writing profile file to stdout

cmd/mdmctl/apply.go
now apply profiles and blueprints accepts stdin with the `-f -` flag.
=> accept - for stdin

CHANGELOG.md, cmd/mdmctl/apply_dep_profile.go, crypto/helpers.go
=> Add anchor certificate to DEP profile template

core/apply/service.go, core/apply/service_dep.go, core/list/endpoint.go, core/list/service.go, core/list/service_dep.go, depsync/depsync.go, deptoken/deptopken.go, serve.go
Update DEP Client everywhere after DEP token is added to avoid server restart.
Fixes #174
=> Depsync reload

cmd/mdmctl/apply_dep_profile.go
=> Change anchor flag text

cmd/mdmctl/apply.go, cmd/mdmctl/get.go
Adjust profiles and blueprints CLIs for get/apply commands to have consistent argument names and usage conventions.
=> Consistency of profiles and blueprints CLIs

appmanifest/appmanifest.go, appmanifest/appmanifest_test.go
ported from tools/appmanifest. First step in solving #93, which will let users upload pkgs with `mdmctl`
=> create appmanifest package

appstore/appstore.go, cmd/mdmctl/apply_app.go, cmd/mdmctl/get.go, cmd/mdmctl/get_app.go, core/apply/client.go, core/apply/endpoint.go, core/apply/service.go, core/apply/transport_http.go, core/apply/transport_http_test.go, core/list/client.go, core/list/endpoint.go, core/list/service.go, core/list/transport_http.go, serve.go
For #93 
WIP, added the ability to upload a appmanifest and pkg to the server.
=> add package and manifest file uploads

cmd/mdmctl/apply_app.go
hopefully last bug before new release.
=> reset used io.Reader for pkg upload

Gopkg.lock
Update `Gopkg.lock` for upstream pkcs7 a la micromdm/micromdm#211
=> dep -update (for newer p7)

blueprint/listener.go, checkin/checkin.go, checkin/checkin_test.go, command/command.go, command/command_test.go, core/apply/service.go, core/list/service.go, depsync/depsync.go, deptoken/deptopken.go, device/db.go, pubsub/inmem/consumer.go, pubsub/inmem/inmem_test.go, pubsub/inmem/publisher.go, pubsub/pubsub.go, push/db.go, push/service.go, queue/queue.go, serve.go
Split types from implementation to support multiple pubsub types in the near future.
=> move pubsub inmem to subpackage

README.md
This bothers me more than it should.
=> Administrato

enroll/endpoint.go, enroll/service.go, enroll/transport_http.go, serve.go
Republishing the accidentally deleted #167. Also now synced up to master, no conflicts, and full customization of OTA Payload, Phase 2, and Phase 3/Enrollment profiles utilizing the Profile service/store.
=> Re-implement enrollment and OTA profile customization

enroll/service.go
=> Add com.apple.mdm.per-user-connections to ServerCapabilities

enroll/service.go
=> try to set topic when initializing enroll service

command/event.go
adds missing key to marshal command
=> marshal install_action key

enroll/profile.go, enroll/profile_test.go, enroll/service.go
Exactly as specified in "Structure of MDM Payloads"
=> model AccessRights as OR bit-flags

.circleci/config.yml
Worth it not to care about context compatibility.
=> remove go1.8 compatibility

cmd/mdmctl/mdmcert.go
Simple change, tested and working:
```
./build/darwin/mdmctl mdmcert vendor -sign ...
ls mdm-certificates
PushCertificatePrivateKey.key	PushCertificateRequest.csr	PushCertificateRequest.plist
```
=> Changed output file extension to .plist for PushCertificateRequest

Makefile
=> update makefile to include linux build of mdmctl

checkin/transport_http.go, command/event.go, command/transport_http.go, config/db.go, connect/endpoint.go, connect/transport_http.go, enroll/endpoint.go, push/endpoint.go, push/transport_http.go, serve.go, user/db.go
=> eliminate dead code

connect/endpoint.go, connect/event.go, push/db.go, queue/queue.go, serve.go, user/db.go
=> user checkins

cmd/mdmctl/apply_app.go, cmd/mdmctl/apply_app_test.go
=> correctly encode the pkgurl in the manifest

Dockerfile, Makefile
See #311 
Example usage:
```bash
$ docker run --rm -ti -p 9000:443 \
-v micromdm-config:/var/db/micromdm \
-v $(pwd)/.certs:/.certs \
micromdm/micromdm:latest serve \
-apns-cert /.certs/apns.p12 \
-apns-password NotPublicStuff \
-api-key VerySecretThings \
-server-url https://your-mdm-domain:9000 \
-tls-cert="/.certs/tls-cert.pem" \
-tls-key="/.certs/tls-private.pem"
```
=> Created a Dockerfile

cmd/mdmctl/apply_user.go, cmd/mdmctl/get_users.go, cmd/mdmctl/setup.go, cmd/micromdm/serve.go, platform/api/server/apply/client.go, platform/api/server/apply/endpoint.go, platform/api/server/apply/service.go, platform/api/server/apply/transport_http.go, platform/api/server/list/client.go, platform/api/server/list/endpoint.go, platform/api/server/list/service.go, platform/api/server/list/transport_http.go, platform/blueprint/builtin/db.go, platform/blueprint/server.go, platform/profile/server.go, platform/remove/server.go, platform/user/apply_user.go, platform/user/builtin/db.go, platform/user/client.go, platform/user/list_user.go, platform/user/server.go, platform/user/service.go
=> refactor user api

cmd/mdmctl/apply_app.go, cmd/mdmctl/get_app.go, cmd/mdmctl/setup.go, cmd/micromdm/serve.go, platform/api/server/apply/client.go, platform/api/server/apply/endpoint.go, platform/api/server/apply/service.go, platform/api/server/apply/transport_http.go, platform/api/server/list/client.go, platform/api/server/list/endpoint.go, platform/api/server/list/service.go, platform/api/server/list/transport_http.go, platform/appstore/builtin/appstore.go, platform/appstore/client.go, platform/appstore/get_apps.go, platform/appstore/server.go, platform/appstore/service.go, platform/appstore/upload_app.go, platform/appstore/upload_app_test.go
=> refactor app upload APIs

platform/device/get_devices.go
testing this seems to resolve
https://github.com/micromdm/micromdm/issues/364
=> remove expectation of json from decodeListDeviceRequest

Gopkg.lock
=> Updated mdm lib version

cmd/micromdm/serve.go
=> must start server with api-key

platform/blueprint/builtin/db.go
=> Only allow saving Blueprints with unique names

Gopkg.lock, cmd/mdmctl/mdmcert.download.go, cmd/mdmctl/mdmdctl.go, pkg/crypto/helpers.go, pkg/crypto/mdmcertutil/certutil.go
=> Implement mdmcert.download support in mdmctl

cmd/micromdm/serve.go, dep/depsync/depsync.go
=> Structured logging for depsync

cmd/micromdm/serve.go, dep/depsync/depsync.go, dep/depsync/endpoint.go, dep/depsync/service.go, dep/depsync/transport_http.go
Fixes #175.
**Note**: This PR is against the master branch and so includes the diffs from #403. Once that gets merged I'll rebase and it'll start at just the last diff ae3e32fa82917e322243b150beb23ec421ce2948. GitHub limitation with PRs maybe (or I'm ignorant of some way to link PRs).
=> Add explicit DEP sync now.

CHANGELOG.md
Style borrowed from [autopkg](https://github.com/autopkg/autopkg/blob/master/CHANGELOG.md).
=> Update ChangeLog with curated list of recent changes & add commit links

cmd/micromdm/serve.go
seems to be returning the correct error with this.  still borks if debug is on, but this should solve for a production environment.
Fixes #388
=> correct header and format for json decoding of error

cmd/micromdm/serve.go
=> Switch for hosting homepage

pkg/crypto/password/password.go
From #430. Don't submit PRs when sleep deprived, folks! 😄
=> Fix bug in compare

tools/api/commands/available_os_updates, tools/api/commands/certificate_list, tools/api/commands/device_information, tools/api/commands/device_lock, tools/api/commands/install_application, tools/api/commands/install_enterprise_application, tools/api/commands/install_profile, tools/api/commands/install_provisioning_profile, tools/api/commands/installed_application_list, tools/api/commands/os_update_status, tools/api/commands/profile_list, tools/api/commands/provisioning_profile_list, tools/api/commands/remove_profile, tools/api/commands/remove_provisioning_profile, tools/api/commands/restart_device, tools/api/commands/schedule_os_update, tools/api/commands/schedule_os_update_scan, tools/api/commands/security_info, tools/api/get_devices, tools/api/send_push_notification
Also fix get devices requiring some body content.
=> Allow setting curl options in environment variable

CHANGELOG.md, mdm/acknowledge.go, mdm/checkin.go, mdm/checkin_test.go
=> decode URL params into webhook event

server/server.go
Worked accidentally removed in refactor under #458.
=> Add back push worker init

cmd/mdmctl/apply.go
=> Use config for block push

CHANGELOG.md, dep/depsync/depsync.go
Re-try fetch after invalid cursor
=> Re-fetch on invalid cursor

platform/device/client.go, platform/device/server.go, tools/api/get_devices
Changed GET to POST as a GET with a request body is not preferred.
=> GET to POST for v1/devices endpoint

platform/profile/client.go, platform/profile/server.go
Changed GET to POST as a GET with a request body is not preferred.
=> GET to POST for v1/profiles endpoint

cmd/micromdm/serve.go, pkg/httputil/httputil.go
Allow live backup of BoltDB over HTTP endpoint.
=> Bolt backup endpoint

cmd/mdmctl/get.go
Resolves https://github.com/micromdm/micromdm/issues/270
=> Allow singulars for devices

vpp/client.go, vpp/clientconfigsrv.go, vpp/getlicensessrv.go, vpp/getvppassetssrv.go, vpp/managevpplicensesbyadamidsrv.go, vpp/vppserviceconfigsrv.go
Currently includes methods to create a vpp client with an sToken, set client context, and associate and disassociate serials to and from vpp apps.
=> Adding a VPP Package

cmd/mdmctl/config.go
=> Initialize empty server config map

CHANGELOG.md, cmd/mdmctl/config.go
=> By default, switch to the new config

CHANGELOG.md, mdm/mdm/command.go, mdm/mdm/internal/mdmproto/mdm.pb.go, mdm/mdm/internal/mdmproto/mdm.proto, mdm/mdm/marshal_json.go, mdm/mdm/marshal_plist.go, mdm/mdm/marshal_proto.go, mdm/mdm/unmarshal_json.go, mdm/mdm/unmarshal_plist.go, mdm/mdm/unmarshal_proto.go, tools/api/commands/activation_lock_bypass_code
Allow a request to be sent to an iOS device to get an activation lock bypass code.
=> Handle ActivationLockBypassCode Request

mdm/mdm/command.go
=> typo in acct config struct

mdm/mdm/command.go, mdm/mdm/marshal_proto.go, mdm/mdm/unmarshal_proto.go
There was a problem of serialization for InstallApplicationOptions.PurchaseMethod = 0.
=> Serialization of InstallApplicationOptions is fixed.

cmd/mdmctl/get_dep_devices.go
Added additional column for DeviceFamily in output of mdmctl get dev-devices -serials=SERIALNUMBER
=> Added DeviceFamily to get dev-devices output, Fixes #81

docs/user-guide/quickstart.md
Updating and cleaning up the documentation for this section.
=> Updating Generate MDM CSR section

cmd/mdmctl/remove_devices.go
=> Adding usage for `mdmctl remove devices`

CHANGELOG.md, cmd/mdmctl/get.go, cmd/mdmctl/get_dep_devices.go, cmd/mdmctl/remove_blueprints.go, cmd/mdmctl/remove_devices.go, cmd/mdmctl/remove_profiles.go
=> Fixes serial[s] flag to match other commands

platform/config/builtin/db_deptoken.go
The server uses only the very first DEP Token when it starts up, here:
https://github.com/micromdm/micromdm/blob/ea393e9804393beab0da9f4b8d2ae3d251828a68/server/server.go#L263-L272
In order to better facilitate this try to order the returned DEP token array by preferring the last one that was added first.
Fixes #546. _Technically_ this isn't quite a "fix" as it's not a way to delete tokens, but I think fixes the problem that occurs when updating a DEP token.
=> Save a record of the last imported DEP token and prefer that one.

platform/dep/sync/depsync.go
Fixes #582. Also add logging & make more consistent; de-dup some code; and minor clean up.
=> Rework the DEP sync runner loop

platform/blueprint/builtin/db.go
=> Protect against nil blueprint

mdm/mdm/internal/mdmproto/mdm.proto, mdm/mdm/marshal_json.go, mdm/mdm/marshal_plist.go, mdm/mdm/marshal_proto.go, mdm/mdm/mdm_command_test.go, mdm/mdm/unmarshal_json.go, mdm/mdm/unmarshal_plist.go, mdm/mdm/unmarshal_proto.go, tools/api/commands/disable_remote_desktop, tools/api/commands/enable_remote_desktop
Add ability to send EnableRemoteDesktop and DisableRemoteDesktop mdm-commands:
https://developer.apple.com/documentation/devicemanagement/enable_remote_desktop
=> Add EnableRemoteDesktop and DisableRemoteDesktop

CHANGELOG.md, cmd/mdmctl/apply.go, go.mod, go.sum, mdm/acknowledge.go, mdm/checkin.go, mdm/enroll/profile.go, mdm/mdm/command.go, platform/command/event.go, platform/dep/sync/event.go, platform/device/worker.go, platform/user/user.go, platform/user/worker.go, vpp/clientconfigsrv.go
replaced the satori/uuid package which was no longer maintained
Closes #664
=> replace UUID dependency

platform/dep/client.go, platform/dep/remove_profile.go, platform/dep/server.go, platform/dep/service.go
Adds the ability to send a DELETE request to clear the DEP profile assignment for one or more serial numbers.
```
DELETE /v1/dep/profiles
{
"serials" : [a,b,c,d]
}
```
=> DEP Remove Profile

cmd/micromdm/micromdm.go, cmd/micromdm/server.go, pkg/frontend/frontend.go, ui/includes/404.tmpl, ui/includes/500.tmpl, ui/includes/home.tmpl, ui/layouts/base.tmpl, ui/layouts/nav.tmpl
Added the basics for HTML templates, serving assets and so on.
=> build a simple web framework

mdm/checkin.go, mdm/service.go, platform/queue/queue.go
Fixes #647 and addresses the mentioned symptom in #646.
=> Clear a UDID's command queue during Authenticate Check-in (enrollment)

platform/apns/service.go
=> make http transport for apns proxy-aware

platform/blueprint/worker.go
Implemented from https://github.com/micromdm/micromdm/issues/549. test and it works on our test system to install multiple packages.
=> fix for issue #549: Blueprints InstallApplication array

CHANGELOG.md
=> True-up changes in CHANGELOG

tools/ngrok/configure_mdmctl, tools/ngrok/start_server
Changed pwd commands in ngrok scripts to small letters.
=> Changed pwd command in ngrok scripts to small letters

pkg/crypto/mdmcertutil/certutil.go
[See here](https://github.com/micromdm/micromdm/issues/723#issuecomment-776771010)
=> Fix #723 - Update intermediate cert and signature algorithm

cmd/micromdm/serve.go
Used CSS from https://micromdm.io
=> Spruce up built in webpage

website/content/blog/v2dev-status-update-1.md
=> Fix twitter URL in v2 blog post

website/content/blog/troubleshoot-dep.md
I'm not even sure if you have the blog linked up to a CI/CD pipeline but found the mistake today while troublehsooting.
=> Add single quote to fix log command

mdm/mdm/mdm_command_test.go
Request test case follow up to #754
=> Add a golden path E2E test case for command_uuid

CHANGELOG.md, cmd/micromdm/serve.go
=> Fix nil pointer interface assignment

cmd/mdmctl/mdmcert.go, docs/user-guide/quickstart.md
=> add missing step in "Generate MDM CSR" workflow

CHANGELOG.md, docs/user-guide/api-and-webhooks.md, mdm/service.go, platform/command/server.go, platform/command/service.go, platform/command/view.go, platform/queue/inmem/inmem.go, platform/queue/queue.go, tools/api/inspect_queue
Sorry I haven't tested this at all, I don't have mdm certs set up on this laptop.
=> Add an endpoint to view the device queue

platform/queue/inmem/inmem.go
Added mutex to in memory queue for `q.queue` manipulations as this was causing a lot of panics
=> fix(queue): in memory concurrent r/w panic
