micromdm/micromdm

- docker-compose-v2.yml
Add example docker-compose file using v2 format.
It isn't exactly perfect especially the volume configuration, but it's a fair reference to all of the ENV var parameters.
> docker-compose v2 format example

- management/transport.go
iOS reports differently formatted UDID's than macOS/OSX. Remove for now and validation can be reinstated later.
> Remove UDID length checking

- .travis.yml
At some point in time the Travis CI configuration was removed from the project (looks like a branch deleted around August 2016).
I've made a start on one even though our test coverage isn't great. At least it can catch build errors and sql migration statement problems.
The configuration includes *postgresql* and *redis* services for integration testing later on.
Give it a look over.
> Add new travis CI configuration

- enroll/profile.go
- enroll/service.go
- main.go
- FIX: ConsentText had the wrong struct tag leading to a key called `omitempty` in the enroll plist.
- Enrollment service now takes a TLS certificate in the case that you are using a self-signed certificate, and that certificate is now added as a payload at enrollment time to resolve a possible trust issue when enrolling to a self signed MDM.
> Fix some situations where enrolment could fail

- enroll/service.go
- main.go
macOS ignores malformed subjects and just enrols.
SCEP payload is optional in /mdm/enroll
SCEP challenge is optional in /mdm/enroll (warning about prompt)
Change CA cert to payload type com.apple.security.root
(cherry picked from commit 0d8d092)
> Fix error enrolling iOS Devices due to SCEP Subject arrays being wrongly nested

- main.go
Left warning in, but removed os.Exit until I can determine a reliable method of using the system trust store in a cross-platform way
> FIX: CA roots are not correctly being verified in main.go

- enroll/service.go
- main.go
You can also use any of the SCEP vars in the subject common name, see `/usr/libexec/mdmclient dumpSCEPVars` for reference.
> SCEP request subject is configurable

- Makefile
- app/app.go
- app/config.go
- app/envutils.go
- app/http.go
- app/services.go
- cli/main.go
- enroll/transport.go
- main.go
- release.sh
- version/version.go
Add a config struct and parse CLI flags outside of main.main.
I'm updating the main package because it's gotten long and can be refactored to be more consistent/easier to add to in the future.
> refactor package main

- queue/queue.go
We were immediately using the nil pointer afterwards.
> Fix panic where popFirst() can return nil

- depsync/config.go
- depsync/depsync.go
- serve.go
For #88
load/save DEP cursor boltdb storage. Call sync once cursor is exhausted.
The sync response handling is still a TODO.
> preserve cursor during DEP fetch

- depsync/depsync.go
the new time is every 30 minutes
10 seconds was good for working on this feature, but I fear the rate-limiting gods.
> update the ticker that triggers DEP sync events

- queue/queue.go
- queue/queue_test.go
Noticed that empty command queues were throwing a 500 error to clients. Catch that and handle a little more gracefully.
> Avoid 500 response for empty command queue

- serve.go
Note that this is just a stop-gap to prevent an add'l dialog during a manual enrollment. We still want to implement #81.
> Add static SCEP challenge to avoid SCEP prompt at manual enrollment

- push/service.go
according to the library docs, a nil context should never be passed
context.TODO() returns an empty context value instead: https://golang.org/pkg/context/
> use context.TODO instead of nil context

- cmd/mdmctl/config.go
`mdmctl config print` shows the current MDM server config. 
In the future I'd like to support fast user switching to multiple servers as well.
> helper to print mdmctl config

- core/list/client.go
Forgot to mention: this allows having a custom `httptransport.SetClient` to allow `InsecureSkipVerify` to be configured for `mdmctl`.
> Use httptransport.ClientOptions in get (list) client

- Gopkg.lock
- command/endpoint.go
- command/transport_http_test.go
Fixes issues introduced by 
https://github.com/micromdm/mdm/pull/15 
https://github.com/micromdm/mdm/pull/16 
and solved in
https://github.com/micromdm/mdm/pull/17
The micromdm/mdm library changed the structure of  the `mdm.CommandRequest` field, causing the decode method to panic. Fixed and added test.
> Fix nil panic on command request API

- Gopkg.lock
main purpose is to update the plist library so recent changes to Marshalling/Unmarshalling from #183 actually work.
Also updating `micromdm/dep` to add tvOS fields.
> update lockfile for latest dependencies

- cmd/mdmctl/apply.go
- cmd/mdmctl/apply_app.go
- cmd/mdmctl/sign.go
- cmd/mdmctl/sign_darwin.go
generate an appmanifest. validates and optionally signs packages.
For #93 
No support for uploads yet, but I'll handle that in another PR. 
The package validates signature but not if the pkg is a distribution package. This is a TODO, as I wasn't sure what the best mechanism for checking that information would be. 
Usage: 
```
USAGE
mdmctl apply app [flags]
FLAGS
-manifest -        path to an app manifest. optional,
will be created if file does not exist.
-md5size 10485760  md5 hash size in bytes (optional)
-pkg               path to a distribution pkg.
-pkg-url           use custom pkg url
-sign              sign package before importing, requires specifying a product ID (optional)
```
Example:
```
mdmctl apply app -pkg ~/Downloads/munkitools-2.8.2.2855.pkg -sign "Developer ID Installer: …
```
> mdmctl: support generating appmanifest

- blueprint/db.go
- cmd/mdmctl/mdmdctl.go
- cmd/mdmctl/remove.go
- cmd/mdmctl/remove_blueprints.go
- cmd/mdmctl/remove_profiles.go
- core/remove/client.go
- core/remove/endpoint.go
- core/remove/service.go
- core/remove/transport_http.go
- profile/db.go
- serve.go
Adds `DELETE /v1/profiles` and `DELETE /v1/blueprints` endpoints along with accompanying `mdmctl remove profiles` and `mdmctl remove blueprints` commands.
> Implement Profile and Blueprint removal APIs and mdmctl UI

- .circleci/config.yml
Updates the CircleCI config to use the Workflows feature, which allows
testing multiple Go versions.
> use CircleCI workflows to create build matrix.

- cmd/mdmctl/apply.go
- cmd/mdmctl/get.go
- cmd/mdmctl/mdmcert.go
Adds default paths to save the DEP token and public key for the
dep-tokens commands.
> mdmctl dep-tokens provide defaults

- Gopkg.lock
- Gopkg.toml
Bring dependencies up to date
```PROJECT                             CONSTRAINT  VERSION        REVISION  LATEST   PKGS USED
github.com/RobotsAndPencils/buford  *           v0.12.0        1589c17   1589c17  3
github.com/boltdb/bolt              ^1.3.0      v1.3.1         2f1ce7a   2f1ce7a  1
github.com/fullsailor/pkcs7         *           branch master  a009d8d   a009d8d  1
github.com/garyburd/go-oauth        *           branch master  4cff9ef   4cff9ef  1
github.com/go-kit/kit               ^0.6.0      v0.6.0         4dc7be5   4dc7be5  5
github.com/go-logfmt/logfmt         *           v0.3.0         390ab79   390ab79  1
github.com/go-stack/stack           *           v1.6.0         817915b   817915b  1
github.com/gogo/protobuf            *           v0.5           342cbe0   342cbe0  1 …
```
> refresh lockfile

- cmd/mdmctl/get_app.go
This will fix the formatting issue, but when trying to test it, I realized the help page doesn't show apps as a valid subcommand:
```
mdmctl get apps                          1 ↵  4922  07:58:34
Display one or many resources.
Valid resource types:
* devices
* blueprints
Examples:
mdmctl get devices
mdmctl get devices -serial=C02ABCDEF****
```
I could run mdmctl get devices and see the header, but it threw an error about connecting to the server (which is fine), but apps displayed help. Either `apps` is not registered as a subcommand of mdmctl or I'm doing it wrong ;)
> Fixed formatting in mdmctl for #240

- cmd/mdmctl/config.go
Looks like what we want now:
```
./build/darwin/mdmctl config set -api-token='secret' -server-url=http://localhost:8000
http://localhost:8000
./build/darwin/mdmctl config set -api-token='secret' -server-url=https://localhost:8000
https://localhost:8000
./build/darwin/mdmctl config set -api-token='secret' -server-url=localhost:8000
https://localhost:8000
```
> Fixed https prepend logic

- cmd/mdmctl/config.go
- cmd/mdmctl/config_test.go
Used `mdmctl confing print` to validate insteasd of fmt.Println().
```
./build/darwin/mdmctl config set -api-token='secret' -server-url=https://localhost:8000
./build/darwin/mdmctl config print
{
"api_token": "secret",
"server_url": "https://localhost:8000/",
"skip_verify": false
}
./build/darwin/mdmctl config set -api-token='secret' -server-url=https://localhost:8000/
./build/darwin/mdmctl config print
{
"api_token": "secret",
"server_url": "https://localhost:8000/",
"skip_verify": false
}
./build/darwin/mdmctl config set -api-token='secret' -server-url=http://localhost:8000
./build/darwin/mdmctl config print
{
"api_token": "secret",
"server_url": "http://localhost:8000/",
"skip_verify": false
}
./build/darwin/mdmctl config set -api-token='secret' -server-url=localhost:8000 …
```
> Remove u.Scheme as we are handling that just before parsing

- serve.go
Closes #267 
The default BoltDB configuration tries to establish a file lock forever and if two instances of micromdm are started, the second instance prevents the server from starting up.
> timeout boltdb open connections after 1 second

- config/db.go
- crypto/helpers.go
- serve.go
The MDM Certificate should now be uploaded instead of specified in a
flag, but the flag should still work for backwards compatibility.
Closes #260
> use the topic from -apns-cert if specified

- cmd/mdmctl/mdmcert.go
- serve.go
fixes a few small issues related to starting a server with the deprecated -apns-cert flag.
> create push service from TLS cert if there's no cert in the DB

- cmd/mdmctl/get_dep_profiles.go
Closes #288 
```
mdmctl get dep-profiles
The DEP API does not support listing profiles.
A UUID flag must be specified. To get currently assigned profile UUIDs run
mdmctl get dep-devices -serials=serial1,serial2,serial3
The output of the dep-devices response will contain the profile UUIDs.
USAGE
mdmctl get dep-profiles [flags]
FLAGS
-f      filename of DEP profile to apply
-uuid   DEP Profile UUID
```
Good short term fix, in the future it would be great to also cache known UUIDs and print them out instead.
> add usage text for dep-profiles

- cmd/mdmctl/apply.go
- cmd/mdmctl/get.go
- cmd/mdmctl/remove.go
- cmd/mdmctl/remove_profiles.go
- cmd/mdmctl/setup.go
- cmd/micromdm/serve.go
- mdm/enroll/service.go
- platform/api/server/apply/client.go
- platform/api/server/apply/endpoint.go
- platform/api/server/apply/service.go
- platform/api/server/apply/transport_http.go
- platform/api/server/list/client.go
- platform/api/server/list/endpoint.go
- platform/api/server/list/service.go
- platform/api/server/list/transport_http.go
- platform/api/server/remove/client.go
- platform/api/server/remove/endpoint.go
- platform/api/server/remove/service.go
- platform/api/server/remove/transport_http.go
- platform/blueprint/db.go
- platform/profile/apply_profile.go
- platform/profile/builtin/db.go
- platform/profile/client.go
- platform/profile/get_profiles.go
- platform/profile/remove_profiles.go
- platform/profile/server.go
- platform/profile/service.go
Moved all the endpoints into the profile package.
Defined a Store interface which includes all the used BoltDB methods.
Moved the BoltDB implementation into a sub-package.
Closes #304 
Closes #305
> reorganize profile service

- platform/remove/builtin/db.go
- platform/remove/remove.go
This was manifesting in every connect command failing for every device because no device was yet in the block (remove) database during the middleware calls. The `isNotFound()` check was failing because the returned error was not an `notFound{}`, instead the new error that errors.Wrap wrapped it in.
> Fix issue where errors.Wrap()-ing an error hides its interface type

- platform/command/transport_http.go
When you take a large-ish profile (for example), add the data encoding (base64) then wrap it in another encoding (JSON) it can get above the 10k limit. Bump up that limit.
> Raise command API limit

- Makefile
Only set Docker image name variable if it's not already defined, so that it's easier to build and distribute internal test builds via Docker hub.
> Default value for DOCKER_IMAGE_NAME if not already set

- mdm/checkin/endpoint.go
- mdm/checkin/transport_http.go
I could have sworn we were doing this already, but I think I got confused with [commandment](https://github.com/cmdmnt/commandment/blob/9258be54b9ba9c0595768da02fa6ee8fb6054163/commandment/mdm/app.py#L155-L157) where it was implemented it. :)
In any case this will reject UserAuthentication attempts with the special 410 (Gone) HTTP status code per the MDM spec. This is for two reasons. One is when I recall in my testing that when you reject the UserAuthenticate message you don't get [the prompt for management settings](https://derflounder.wordpress.com/2013/11/13/bypassing-the-mavericks-managed-preferences-login-check/). The other is that we probably shouldn't be sending the wrong response. We appear to be sending an a 401 response for unknown Checkin request MessageTypes which I'm not …
> Reject UserAuthentication attempts per MDM spec

- platform/device/builtin/db.go
The error I was seeing was if I changed the serial number in a VM and then re-enrolled the server would create a second record for the same UDID. I recreated this condition using the ngrok set ups and then saving an example of a `checkin` request. I think changed the serial number and replayed and each time I changed and replayed I got a new device record.
Looking at the device db it looks like we weren't using the device we looked up in the `DeviceByUDID` call.
After apply this patch and retrying my testing above I instead see the serial number updated on the existing record vs a new record with the same udid.
This might be related to https://github.com/micromdm/micromdm/issues/402 but that case is slightly different. That was the udid changing but the serial number staying the same and …
> Prevent multiple device records with the same UDID

- cmd/mdmctl/config.go
Fixes issue in https://github.com/micromdm/micromdm/issues/371
I made the `-server-url` and `-api-token` flags required parameters. Additionally if set is called with no arguments at all the help is printed.
I also added a fix to make sure the switch command only allows you to switch to a server config that exists
> Do not allow `mdmctl config set` without args

- cmd/micromdm/serve.go
- platform/device/builtin/db.go
- platform/device/builtin/db_test.go
- platform/device/worker.go
Move the code for polling topics and updating device records into an independent worker.
Cleans up the code and makes it possible to swap the db backend.
> decouple device updates from db CRUD

- platform/device/worker.go
Fixes a bug with the device worker where newly enrolled devices didn't publish an enrollment message. This caused profiles and apps to not be pushed down to the device
> Ensure enrollment message is published for newly enrolled devices

- Dockerfile
It was 3.6, but now it's 3.7! Also removed some superfluous whitespace.
> Update base container to Alpine 3.7

- platform/user/worker.go
UUID was missing on Checkin for user and erroring out in bolt for lacking a key. Probably just a simple typo in the worker refactors.
> Fix code-never-reached situation

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- tools/api/README.md
- tools/ngrok/README.md
I was just browsing around the docs and my editor trimmed out trailing whitespace.
> Remove superfluous whitespace from markdown files

- Gopkg.lock
- Gopkg.toml
- cmd/micromdm/serve.go
micromdm/scep#87 is still open for that project. But this PR should resolve #436 (as we're compiling against the fixed version of pkcs7 in @groob's branch). I've tested with a 10.12.6 VM and it seems to enroll fine, but could definitely use some testing.
I'm not super sure about the Handler changes. I feel there's a better way to do this, especially with the doubled-up path Handlers in both the scepserver MakeHandlers, and the r.Handler in micromdm. Also - the `dep` tool stuff is a bit of a nightmare, if folks can test to make sure they're `dep ensure` works fine that'd be great, too.
Feedback welcome!
> Use micromdm/scep master (for newer pkcs7 lib)

- cmd/micromdm/serve.go
- platform/apns/builtin/db.go
- platform/apns/worker.go
Separates out the event listener worker from the DB code in the Push subsystem. This will allow easier support of different DB implementations in the future.
> Create pushinfo Worker separate from DB implementation

- cmd/mdmctl/remove.go
- cmd/mdmctl/remove_devices.go
- platform/device/builtin/db.go
- platform/device/builtin/db_test.go
- platform/device/client.go
- platform/device/remove_devices.go
- platform/device/server.go
- platform/device/service.go
This adds a `remove devices` command to `mdmctl`. You can pass a single UDID or a comma separated list of UDIDs. Only the device records are removed.
Resolves #394
> Allow removal of device records

- platform/apns/service.go
In order to set custom transport options on the http.Client used
by the push service we need to create our own instance. This
allows us to configure the IdleConnTimeout and prevent connections
from being killed and pushes not being sent. 90 seconds is used
here since it's the same as the DefaultTransport provided by Go.
Fixes #215
> Create a custom http.Client for apns communication

- Gopkg.lock
- Gopkg.toml
Resolves https://github.com/micromdm/micromdm/issues/453
This is a temporary fix until the proper CBC variant for content encryption is implemented in pkcs7
> pin to aes_fix branch

- tools/api/commands/device_information
Adds support for specifying query strings with tools/api/commands/device_information example.
Invoking:
`./tools/api/commands/device_information 9824c12e8cb0feed3cfae91e8ec9b37dc5e019fe "OSVersion,Model,ModelName,BatteryLevel"`
Gets you:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CommandUUID</key>
<string>195e7036-1bbc-4e20-a428-1799c10327f2</string>
<key>QueryResponses</key>
<dict>
<key>BatteryLevel</key>
<real>0.86000001430511475</real>
<key>Model</key>
<string>MF519LL</string>
<key>ModelName</key>
<string>iPad</string>
<key>OSVersion</key>
<string>10.3.3</string>
</dict>
<key>Status</key>
<string>Acknowledged</string>
<key>UDID</key> …
```
> DeviceInformation command API example support query strings

- .gitignore
- tools/api/sync_dep_devices
This adds `sync_dep_devices` in the api tools.
Also I saw that .DS_Store files are not in the .gitignore, so I added that as well.
> Sync dep devices tool

- Makefile
regression per https://github.com/golang/go/issues/27285 which states we don't need `-i` anymore? literally have done zero looking into if this the right thing. just fixed builds for me.
> Remove go build -i

- platform/config/builtin/db.go
- platform/config/get_push_certificate.go
- platform/config/server.go
- platform/config/service.go
Allow reading the MDM push cert from the server. To e.g. periodically check its expiration or to idempotently update the push cert.
> Retrieve certificate

- platform/appstore/client.go
- platform/appstore/server.go
Changed GET to POST for "get apps" as a GET with a request body is not preferred.
Changed POST to PUT for "upload apps" as POST is now used for "get apps".
> GET to POST and POST to PUT for v1/apps endpoint

- platform/blueprint/client.go
- platform/blueprint/server.go
Changed GET to POST as a GET with a request body is not preferred.
> GET to POST for v1/blueprints endpoint

- tools/api/commands/install_profile
- tools/api/commands/install_provisioning_profile
When running the `api/commands/install_profile $udid "/Library/Managed Installs/profile.mobileconfig"` command (or anything with a space in the environment variable), the command returns:
`cat: /Library/Managed: No such file or directory`
`cat: Installs/profile.mobileconfig: No such file or directory`
Added quotes around the variable to fix.
> Updating to allow spaces in environment variable

- CHANGELOG.md
- cmd/micromdm/serve.go
- server/server.go
allows admins to set a desired scep client validity in days as an argument to `micromdm serve`.  default will still be 365.
> variable scep client validity

- platform/queue/queue.go
quick resolve for https://github.com/micromdm/micromdm/issues/580
this just ensures that each time a command is moved to completed it's time is recorded in the struct.  useful to prune completed commands by date.
> set acknowledge time when moving command to completed queue

- docs/architecture/2019-05-03_no_device_configured_without_blueprint.md
- platform/blueprint/worker.go
https://github.com/groob/micromdm/blob/44b54146be9502e6c5fdbf4c1825c1d3b1381adb/docs/architecture/2019-05-03_no_device_configured_without_blueprint.md
> Do not send DeviceConfigured when there are no user configured blueprints

- CHANGELOG.md
- cmd/mdmctl/apply.go
- docs/user-guide/enrolling-devices.md
- docs/user-guide/mdmctl-signing-profiles.md
- pkg/crypto/profileutil/sign.go
```
mdmctl apply profiles -help
Upload profiles to the server.
Uploaded profiles can also be specified in a blueprint, which will be applied on device enrollment.
This command can also be used to replace the enrollment profile.
Profiles can be signed before upload.
Examples
mdmctl apply profiles -f /path/to/profile.mobileconfig
mdmctl apply profiles -f /path/to/profile.mobileconfig -private-key key.pem -cert certificate.pem -password secret -sign
mdmctl apply profiles -f /path/to/profile.mobileconfig -private-key key.pem -cert certificate.pem -password secret -sign -out signed.mobileconfig
USAGE
mdmctl apply profiles [flags]
FLAGS
-cert          Path to the signing certificate or p12 file.
-f             Path to profile payload.
-out           Output path for signed profile(optional). …
```
> mdmctl: add options to sign a profile

- CHANGELOG.md
- platform/apns/push.go
- platform/apns/service.go
When sending a push notification, allow adding an ?expiration=<unix_epoch_time> value.
Apple will retry delivery until this time. The default behavior only tries once.
> apns: Add ability to set an APNS message expiration.

- platform/dep/assign_profile.go
- platform/dep/client.go
- platform/dep/server.go
- platform/dep/service.go
Adds the ability to send a POST request to assign one or more serials to
a profile ID that was defined with the define profile endpoint.
```
POST /v1/dep/assign
{
"id" : "profile_id",
"serials" : [a,b,c,d]
}
```
> add assign profile endpoint

- platform/device/get_devices.go
Right now this doesn't work - but it should from what I can see. Opening this PR so we can get this working.
This actually returns
```
{
"devices": [
{
"serial_number": "SERIAL",
"udid": "UDID",
"enrollment_status": true,
"last_seen": "2019-09-05T01:32:33.994054Z",
"dep_profile_status": ""
}
]
}
```
But I would expect it to default to `empty` looking at https://github.com/micromdm/micromdm/blob/master/platform/device/device.go#L45-L53
> Add DEPProfileStatus to API response

- cmd/micromdm/serve.go
- platform/queue/queue.go
- server/server.go
MicroMDM currently saves all commands it has sent. Further, it stores these on a single device record in the database. This has lead to scalability issue that creates a race condition as noted in #556. This PR creates an option to simply skip saving these historical commands to the database.
> Add option to opt out of saving device command history

- CHANGELOG.md
- cmd/micromdm/serve.go
- mdm/enroll/service.go
- platform/challenge/challenge.go
- platform/challenge/server.go
- platform/challenge/service.go
- server/server.go
This integrates optional dynamic SCEP challenge support. This means that the MicroMDM SCEP server will require a pre-generated random SCEP challenge before issuing a certificate (and thus allowing enrollment into MDM) if the `-use-dynamic-challege` is set. In order for a device to successfully enroll using this method the SCEP challenge must be present in the enrollment profile SCEP payload that is sent to the device. Think of it like an enrollment passcode.
To generate your own enrollment profiles you'll want to use this new API endpoint of `/v1/challenge` which generates, stores, and returns the one-time SCEP challenge which should be embedded in an enrollment profile.
Interestingly, the SCEP server code for this has been written for quite some time (thanks, @groob!). I believe this …
> dynamic SCEP challenge support

- mdm/enroll/profile.go
This reverts commit 2f2616e274052529d50fb7e2d655a629a205c8d1 (#492). It appears the old PDF docs were incorrect and the keys with spaces are actually correct as documented here: https://developer.apple.com/documentation/devicemanagement/scep/payloadcontent#properties
> Revert "Correct SCEP profile payload (#492)"

- dep/profile.go
the server response in this case is a nested `map[string]string`
> correctly handle the response object for remove profile

- cmd/mdmctl/mdmcert.go
> Fix a typo in command usage

- .gitignore
- dep/activation_lock.go
- pkg/activationlock/activationlock.go
- pkg/activationlock/activationlock_test.go
Codes to lock and unlock the device. 
https://developer.apple.com/documentation/devicemanagement/device_assignment/activation_lock_a_device/creating_and_using_bypass_codes
Send the hash to mdmenrollment.apple.com to lock.
To unlock, either type the human readable code string in Setup Assistant, or send it to deviceservices-external.apple.com/deviceservicesworkers/escrowKeyUnlock.
> add activation lock bypass code creation

- docs/user-guide/introduction.md
The URL to join MacAdmins Slack group was an error page at "macadmins.herokuapp.com". I assume this is the old address and should be "www.macadmins.org".
> Updated URL to join MacAdmins Slack group

- mdm/checkin_event.go
Corrected typo in plist encoding tag of auth.Model struct property and in a comment.
> Typo in plist encoding tag and a comment.

- cmd/mdmctl/config.go
- cmd/mdmctl/config_test.go
- pkg/httputil/httputil.go
Updated mdmctl to allow its base server URL to have a path. For example: `https://www.example.com/test/`
The first MicroMDM server I configured required that its base URL have a path. When I set my local mdmctl server url with a path, I didn't realize mdmctl removed it. My commands failed with confusing errors. For example, `mdmctl get devices` returned "invalid character 'O' looking for beginning of value".
It took me a little while to figure out the server url path was removed. Then, I tried editing servers.json directly and added the server path. mdmctl still did not work because it removed the path again after the server URL was loaded from servers.json. This exercise took some time troubleshooting. I'd like to prevent this from happening to others.
> Updated mdmctl to allow base server URL to have a path

- cmd/micromdm/micromdm.go
- cmd/micromdm/micromdm_test.go
- cmd/micromdm/swap_signal.go
- cmd/micromdm/swap_signal_windows.go
Added tests to validate the process receiving signals:
- SIGTERM and SIGINT exit.
- SIGUSR2 swaps logs
Removed the empty Fprintln in main. Turns out stderr isn't thread safe
to write from multiple locations. The logger, which is otherwise the
only stderr writing goroutine creates a sync writer. But the stderr in
main remains unsafe. This is something to fix later?
There are also races happening with the swap log test, but only when the
test runs in parallel. I'm not sure what's happening there... added a
flag to make this test synchronous for now.
> Add signal tests for main

- platform/queue/command_queued.go
When a QueueCommandQueued is marshaled in MarshalQueuedCommand, the QueueCommandQueued.DeviceUDID was copied to the protobuf CommandUuid property. Now the CommandUUID property is copied to the protobuf CommandUuid property.
> MarshalQueuedCommand property mismatch

- CHANGELOG.md
- cmd/micromdm/serve.go
- server/devicecert.go
- server/server.go
Currently we're only verifying whether the cert presented is present in the database. For reasons I don't understand / have time to investigate, clients have valid SCEP certificates which aren't stored in the database. This PR adds an option to validate only the Issuer and the CA that signed the cert.
> Option to validate only CA and Issuer rather than entire SCEP cert

- cmd/micromdm/serve.go
- platform/device/udidauth.go
- server/server.go
Currently the UDID Cert Auth middleware (#358) rejects connections for mismatched certificates. However, if you have a legitimate reason to allow non-matching certificates (say, you have active enrollments for which [end-users renewed their own certificates](https://github.com/micromdm/micromdm/wiki/Device-Identity-Certificate-Expiration)) you may want to disable the connection rejection while you remediate those enrollments.
I'm not entirely convinced this should even be merged as it actively subverts a security measure. Thoughts welcome.
> UDID Cert Auth: warn only option

- platform/queue/queue.go
When there's no new command and there's an `Idle` connect there's no need to re-write the queue for a device back out — nothing's changed. Saves a BoltDB write operation in that case.
> Avoid queue save when not needed

- mdm/mdm/command.go
- mdm/mdm/mdm_command_test.go
Fix for Issue #703. I'm not really sure how to add unit tests, but I did perform the following on a test MacBook:
| Current Local Password | CurrentPassword | NewPassword | Result | Notes |
| -------------------------------- | ----------------------- | ------------------- | --------- | -------- |
| test | *empty* | test | Current password not provided | |
| test | test | test | **PasswordChanged** | |
| test | test | *empty* | A firmware password change is already pending. Machine must be rebooted before any additional change requests are accepted. | Oops - good to know |
| test | test | *empty* | **PasswordChanged** | After reboot |
| *empty* | test | test | **PasswordChanged** | If local password is blank, it doesn't matter what you pass in CurrentPassword |
Seems like everything is …
> Fix SetFirmwarePassword and VerifyFirmwarePassword parameters

- cmd/mdmctl/get_dep_profiles.go
TIL you can download a DEP profile with mdmctl. Correcting the mdmctl help info should make this more obvious.
> Correct mdmctl dep-profiles flag

- cmd/micromdm/serve.go
Following up on #721 (I was out when I got messages from @williamtheaker), I've added a few extras to the changes proposed there.
While the SVG a11y APIs should ensure that this SVG isn't exposed to assistive technologies, I've added `aria-hidden="true"` to ensure that the content is not exposed to users.
Similarly, while this bug is generally windows-based, and increasingly rare, some OS / browser combinations make all SVG elements focusable via the keyboard by default, so I've added `focusable="false"` to prevent that from happening in these odd corner cases.
Let me know if you have any questions here!
> Ensuring MicroMDM Logos are Hidden to assistive technologies

- mdm/checkin.go
- mdm/service.go
- platform/device/udidauth.go
- platform/remove/remove.go
- server/devicecert.go
Currently all of the Checkin messages don't return a response—they all succeed without any return value. However, certain Check-in messages require returning a payload such as `UserAuthenticate`, `GetBootstrapToken`, `DeclarativeManagement`, etc.
This PR adjusts the check-in interface to allow for returning payload data on a Check-in message which gets returned to the client verbatim (much like the `Acknolwedge` interface method already does). Note this PR does not implement any of the above; rather it just makes it possible for them to be implemented.
> Refactor MDM service to return a payload from check-ins

- go.mod
- go.sum
Update scep & pkcs7 to latest. This also avoids having to replace our dependency of pkcs7 to the forked version.
> Update scep and pkcs7

- platform/dep/sync/depsync.go
In case the process & publish fails don't save our cursor until after that's done. In this way we can give those synced devices a chance.
> Process devices before we sync

- .github/workflows/CI.yml
- Dockerfile
- cmd/mdmctl/sign.go
- go.mod
- pkg/tools/tools.go
- platform/apns/pg/pg_test.go
- platform/device/pg/pg_test.go
This PR does:
- update GitHub action to use 1.16/1.17
- pins golang version in the Dockerfile
- adds go mod tidy and module updates to go.mod
- bump go version to 1.17
> Golang updates

- cmd/mdmctl/config.go
`mdmctl config switch` currently doesn't provide any hint that a `-name` flag should be passed:
```
% ./mdmctl config switch
no server named "" found
% ./mdmctl config switch example
no server named "" found
```
After this patch:
```
% build/darwin/mdmctl config switch
USAGE
mdmctl config switch [flags]
FLAGS
-name   name of the server to switch to
```
> Show mdmctl config switch usage if no server -name passed

- pkg/crypto/mdmcertutil/certutil.go
Hi! Today I was renewing my certificates and I found an error while signing the push certificate:
```
$ ./mdmctl mdmcert vendor -sign -cert=./mdm-certificates/mdm.cer -password=MyAwesomePassword
signing push certificate request with vendor private key: load root certificate from http://www.apple.com/appleca/AppleIncRootCertificate.cer: got 502 Bad Gateway when trying to http.Get http://www.apple.com/appleca/AppleIncRootCertificate.cer
```
I tried to get the certfile using wget using the same url and it throws the same error. The only way to retrieve that file was to communicate using https.
I know this pull request is trivial (I only added an 's' to the url) but I was able to create and sign my push certificate after this change.
> Fix to 502 Bad Gateway error while communicating with Apple Servers

- go.mod
- go.sum
- mdm/mdm/mdm_command_test.go
There's currently an issue as noted on the MacAdmins slack with the RotateFileVaultKey command panicking in certain cases due to a edge case in the plist library.
This PR adds a test for the panic case and updates the plist library to [the fixed version](https://github.com/groob/plist/pull/36).
> Fix RotateFileVaultKey panics

- pkg/httputil/httputil.go
- platform/config/client.go
- platform/dep/client.go
- platform/dep/get_account_info.go
- platform/dep/sync/client.go
Per recent conversations on MacAdmins slack, mdmctl sends a request body of `null` or `{}` for:
* `mdmctl get dep-account`
* `mdmctl get dep-autoassigners`
* `mdmctl get dep-tokens`
This happens because `nil` or an empty struct is passed to [EncodeJSONRequest](https://github.com/go-kit/kit/blob/master/transport/http/client.go#L175).
This is problematic for HTTP proxies/load balancers that don't like GET requests with bodies. There's also no reason to send these empty bodies as they're not parsed by the server anyways.
This commit adds a noop `EncodeEmptyRequest` helper and uses it for those `GET` endpoints. It also removes an unused empty struct for the get-account endpoint to match the other two.
I've tested this against MicroMDM v1.9.0.
> mdmctl: don't send a request body for GET requests

- dep/client.go
When the client instance is shared between. multiple go routines, creating a session can result in 429 from Apple
> Make dep client thread safe

- .github/dependabot.yml
- .github/workflows/CI.yml
- .github/workflows/docker.yml
Someone (me) pinned old versions of Github Actions, which is causing deprecation warnings in your actions: `The save-state command is deprecated and will be disabled soon. Please upgrade to using Environment Files.` & `Node.js 12 actions are deprecated.`. This PR enables Dependabot, which will checking for updates and open PRs to bump the pinned version for Github Actions and Go modules.
I've left the checkout action in the Docker worklow one version behind, so you can see an example Dependabot PR upon merging this branch.
I also moved `gofmt` to earlier in the CI run, on the assumption that you don't want to waste minutes building commits that haven't been linted.
> Enable Dependabot version updating.

- mdm/server.go
This PR is to address some issues discovered while [troubleshooting enrollment issues](https://macadmins.slack.com/archives/C19RTE0L9/p1679701827459239) on the MacAdmins Slack:
* The device cert pkcs7 verification currently used on the /mdm/checkin doesn't account for time skew
* Since the device is generating the certificate on the fly, if the device is just a few seconds ahead of the server, the server current time will be outside of the certificate validity, and verification will fail
* This is fixed by adding a 5 minute skew with [VerifyWithChainAtTime](https://pkg.go.dev/go.mozilla.org/pkcs7#PKCS7.VerifyWithChainAtTime)
* Most of the errors in the mdm Endpoints are silently dropped because the response encoder called the error encoder directly, instead of just returning the error so …
> Address issues with /mdm/checkin endpoint

- CHANGELOG.md
- docs/user-guide/api-and-webhooks.md
- platform/command/clear.go
- platform/command/event.go
- platform/command/event_test.go
- platform/command/new_command.go
- platform/command/server.go
- platform/command/service.go
- platform/queue/inmem/inmem.go
- platform/queue/queue.go
- server/server.go
- tools/api/clear_queue
- tools/api/raw_command
Following discussions on the recent office hours, this PR adds support for enqueuing raw plist commands. This PR also adds an endpoint to clear command queues, since a malformed command could break a command queue. Without a way to clear a device's queue, a command queue could become unfixable, short of manually editing the database.
Here's a summary of the changes:
**Raw Command Enqueuing**
* Add POST /v1/command/{udid} endpoint
* The request body is just the raw command plist
* This is similar to NanoMDM's command enqueuing endpoint, though it doesn't currently support multiple ids
* Internally, this is published to a new `command.RawCommandTopic`, which the boltdb and inmem queues have new pollers for
**Clear Device Queue**
* Add DELETE /v1/command/{udid} endpoint
* This uses the …
> Add raw command and clear device queue endpoints

- cmd/micromdm/serve.go
There currently doesn't appear to be a way to have MicroMDM include a timestamp in it's logs. This PR adds a flag (default off) that will set the "ts" log key to the UTC timestamp.
> add flag to include timestamp in logs

- cmd/micromdm/serve.go
- mdm/enroll/transport_http.go
- mdm/server.go
- mdm/server_test.go
- pkg/crypto/helpers.go
This PR is just cherry-picked from the work I previously did in #871.
At the time, I was unable to replicate the clock skew issue, and we only had one report. Since then, there's been a couple of issues ([NanoMDM #71](https://github.com/micromdm/nanomdm/issues/73), #886) reported experiencing the same issue @tgunz first reported on the MacAdmins Slack.
As-is, this adds a flag to configure the clock skew, and it defaults to 0s.
I still think it's worth exploring setting the default to 5 minutes (see [here](https://github.com/micromdm/micromdm/pull/871#issuecomment-1483955814) for why that duration). It would mean the issue is fixed transparently for most users instead of issues being raised here or on the MacAdmins slack.
More importantly, I don't see any downsides to this change. In …
> Add configurable clock skew flag

- .github/workflows/CI.yml
- CHANGELOG.md
- Dockerfile
- cmd/mdmctl/apply.go
- cmd/mdmctl/apply_dep_autoassigner.go
- cmd/mdmctl/config.go
- cmd/mdmctl/get.go
- cmd/mdmctl/get_dep_profiles.go
- cmd/mdmctl/mdmcert.download.go
- cmd/mdmctl/mdmcert.go
- cmd/mdmctl/remove.go
Go 1.20's `test` will fail mdmctl because of strings with trailing newlines. This PR removes the newlines, and adds 1.20 to the build matrix.
I also tidied three minor complaints from staticcheck.
> Chore: tidy for go 1.20

- CHANGELOG.md
- go.mod
- go.sum
(At least sometimes) Apple doesn't include the `signature-creation-time` field in the xar (pkg) TOC.
On non-darwin platforms, mdmctl uses [go-macos-pkg](https://github.com/korylprince/go-macos-pkg), which wraps [my fork of the goxar pkg](https://github.com/korylprince/goxar), to verify that pkgs are signed. goxar uses the presence of the `signature-creation-time` to determine if a pkg is signed, (despite already verifying the signature).
This PR updates go-macos-pkg to v1.3.6, which removes the check for `signature-creation-time`.
> updated to go-macos-pkg v1.3.6

- cmd/micromdm/serve.go
- go.mod
- go.sum
This PR adds a flag to allow disabling the :80 to :443 redirect. This PR is pending merge of https://github.com/micromdm/go4/pull/16 and updating go.mod/go.sum.
> Allow disabling :80 to :443 redirect (Fixes #963)

- platform/dep/sync/depsync.go
Recently on the MacAdmins Slack @trekkim described an issue where the DEP syncer was syncing several times a second.
On [closer inspection](https://macadmins.slack.com/archives/C19RTE0L9/p1721587227194389?thread_ts=1721584429.406019&cid=C19RTE0L9), Apple's response to the fetch devices endpoint used the same cursor sent in the request, and set the `more_to_follow` field to true. This caused MicroMDM to make the same request over and over again in a tight loop.
Ultimately the fix was to delete the "bad" cursor out of the database and start a new sync.
Ideally, Apple would fix this behavior on their side. Until then, this PR adds detection (return same cursor and `more_to_follow`=true) and correction (fetch with an empty cursor) for this situation.
> Add detection of buggy DEP cursors
